from app.investigator.tools import GET_DEPLOYMENTS_TOOL, INCIDENT_TOOL, SEARCH_LOGS_TOOL, GET_METRICS_TOOL

MODEL = "gpt-5.6-luna"
MAX_TOOL_ROUNDS = 3
MAX_MODEL_CALLS = 4
MAX_INVESTIGATION_TOKENS = 20_000
TOOLS = [
    GET_DEPLOYMENTS_TOOL, 
    INCIDENT_TOOL, 
    SEARCH_LOGS_TOOL, 
    GET_METRICS_TOOL,
    ]